### ISSUE TITLE
cutting board crashes when crafting

### ISSUE THREAD

**Issue by ewsmith** [McJty/AquaMunda#1]
using the knife/roller to craft a Thing(tm) makes minecraft cry :'c

[https://gist.github.com/ewsmith/26fbdff63891036bbedf2b8788c30bc8](https://gist.github.com/ewsmith/26fbdff63891036bbedf2b8788c30bc8)

tried with dough and vegetable soup. i used the roller for the dough and the knife for the soup.
i could load the world after the crash and the ingredients where still there without the Thing(tm) being crafted.

edit: as of 17:36 cst usa i opened this 6 hours from now :D

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Not sure what could cause that but I'll add protection to it for next release

**Comment by ewsmith** [comment]
well, the crash changed.  if it makes any difference, i'm on 1.10.2.

[https://gist.github.com/ewsmith/7de9546a8b79320f9a6f3fb06846df0b](https://gist.github.com/ewsmith/7de9546a8b79320f9a6f3fb06846df0b)

**Comment by McJty** [comment]
This is extremely weird. What exactly do you have on your cutting board when this crash occurs?

**Comment by ewsmith** [comment]
i have a carrot on the top left, a beetroot on the top right, and a brown mushroom on the bottom center. then i right click it with the knife.

**Comment by McJty** [comment]
I found the real bug. Will release a fix today
