### ISSUE TITLE
Feature Request: Config/Craft Tweaker hooks to add recipes

### ISSUE THREAD

**Issue by jlbrewer** [McJty/AquaMunda#11]
I'm evaluating mods for a 1.11 pack which includes Pam's Harvestcraft. and will include a lot of Craft Tweaker work.. This mod is relevant to my interests (I'm playing with other mods that alter early game mechanics as well) but to be worth it I'd need to be able to add recipes, either with Aqua Munda's config or Craft Tweaker. How much of a pain would that be to implement?

**Comment by McJty** [comment]
You can already add recipes through the AquaMunda config. See aquamunda_recipes.cfg

**Comment by jlbrewer** [comment]
"Check the config folder before posting", I said. Totally missed the other
config file.

Cheers o/

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jlbrewer** [comment]
One other question, actually. Is is also possible to add grindstone recipes? I've got two mods with corn and cornmeal and other things that would use the mortar and pestle in Pam's might make sense with it.

**Comment by McJty** [comment]
Grindstone recipes are implemented in the upcoming version
