### ISSUE TITLE
Crash with falling Fresh Water

### ISSUE THREAD

**Issue by davqvist** [McJty/AquaMunda#13]
MC 1.10.2
Forge 2297
Aqua Munda 0.1.1beta

I was going to test the gravity of Fresh Water. So I placed it in creative on a block and broke the block under it causing a crash. See crashlog: https://pastebin.com/dBykZFp1

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
This bug only affects the 1.10 version of AquaMunda. 1.11 and 1.12 are fine. I'll implement a workaround
