### ISSUE TITLE
Rendering issue with Fresh Water Tank

### ISSUE THREAD

**Issue by davqvist** [McJty/AquaMunda#15]
MC 1.10.2
Forge 2297
Aqua Munda 0.1.1beta

Sometimes when you look at the tank filled with Fresh Water, the water turns nearly invisible (see-through). I can't tell when exactly it happens. I could achieve it best, when I attach a hose to the tank and look back and forth from hose and tank while standing one block lower than the tank.

**Comment by McJty** [comment]
Will check it out

**Comment by McJty** [comment]
Fixed next release
