### ISSUE TITLE
Cooker w/ Carrot & Potato Dish issue

### ISSUE THREAD

**Issue by Buldr1504** [McJty/AquaMunda#16]
Minecraft: 1.10.2
Forge: 12.18.3.2422
Aqua Munda: 0.1.1 beta

First of all, thank you for all your amazing mods!
 
I tested Aqua Munda, no crashes so far (therefore no log or crash report) and it fits perfectly in the early and mid stage of my mod pack. I found an issue and I’m not sure if it’s a bug or if I’m derping. 

I can’t take a potato or carrot out of the cooker with a bowl in my hand, the soup works fine. 
Step by step description: I put down sticks on cobble, set them on fire with a flint & steel, set up the Cooker, put in a bucket of fresh water, wait till the temperature has reached 100 (maximum) (or put them in before, I tried both) and put in the carrot/potato. After the bar of „One Probe“ is filled up, I try to take the then cooked carrot or potato out with a bowl, but nothing happens. If I break the cooker, I get a cooked potato or carrot.

**Comment by McJty** [comment]
That's as intended. The cooked potato/carrot are meant to be taken out directly. The bowl is only for the soup
