### ISSUE TITLE
Crash when breaking Desalination Tank

### ISSUE THREAD

**Issue by davqvist** [McJty/AquaMunda#17]
MC 1.12
Forge 2443
Aqua Munda 0.1.2beta

When using a Sparks Hammer or a Flexible Tools Pickaxe with Range Upgrade (so I assume it happens with every tool that mines multiple blocks) on a Desalination Tank it causes a crash.

https://pastebin.com/JmxMTZ3S

**Comment by davqvist** [comment]
Apparently some other tools cause it as well, someone crashed with a Stone AIOT from Actually Additions.

**Comment by McJty** [comment]
Fixed next release
