### ISSUE TITLE
[Suggestion] Adding config to disable catching rain water in tank

### ISSUE THREAD

**Issue by davqvist** [McJty/AquaMunda#19]
MC 1.12.1
Forge 2460
AM 0.1.2beta

I wonder if it would be possible to add a config option which disables that the tank collects water from the rain. Reason being that I might add a mod that adds toxic rain and then it wouldn't make thematic sense anymore.

**Comment by McJty** [comment]
Sure. I'll add that next version

**Comment by McJty** [comment]
Both rainfall collection and evaporation will be configurable (with the option to disable) next version
