### ISSUE TITLE
[Question/Bug?] Seeds pop up when not using fresh water

### ISSUE THREAD

**Issue by davqvist** [McJty/AquaMunda#20]
MC 1.12.1
Forge 2460
AM 0.1.2beta

I wonder if it is intentional that seeds that are planted on AM Farmland pop up when not supplied with fresh water nearby. This happens whenever there is a block update, meaning when I plant a seed adjacent to another plant of if a growth tick is applied.

**Comment by McJty** [comment]
What config option did you pick for the farmland mode?

**Comment by davqvist** [comment]
S:farmlandOverhaulType=fresh

But I thought this only affects growth speed and not popping off for seeds.

**Comment by McJty** [comment]
I will check out the exact details soon

**Comment by McJty** [comment]
When no fresh water is available the farmland will turn into dirt and then seeds will pop off. Is that what happens?

**Comment by davqvist** [comment]
No, it is still Farmland. What I expect to be happening is, that when nothing is planted on Farmland and is not watered it gets turned into dirt, but when a seed is planted, it just grows very slowly. This is the same behavior as in vanilla when farmland is not provided with any water nearby.

**Comment by McJty** [comment]
I will investigate

**Comment by davqvist** [comment]
Not sure if it helps but you can see it in action here: https://www.twitch.tv/videos/169003744 starting from 2:55:00
My assumption: Some seeds as Hemp cause a Block update which causes the seeds to pop off. As even the vanilla seeds pop off later (couldn't find the timeframe right now), I assume this is caused by a growth tick.

**Comment by McJty** [comment]
I'm working on Aqua Munda again but I cannot reproduce this problem in my dev env

**Comment by davqvist** [comment]
Definitely happens wirh modded seeds, did you try with Hemp from IE?

**Comment by McJty** [comment]
Well perhaps the modded seeds cannot cope with the fact that Aqua Munda overrides farmland with a custom block. In any case there will be a config option next version to not do that (but with more limited Aqua Munda experience in that case)

**Comment by davqvist** [comment]
Okay, I tested it, couldn't replicate with Hemp anymore for some weird reason, but could definitely replicate with vanilla beetroot. Can you investigate again?

**Comment by McJty** [comment]
Well that test I already did. Exactly what is your setup?

**Comment by davqvist** [comment]
I can definitely replicate in 0,2 again. I just place 2 dirt, hoe them and place two beetroot seeds in both AM Farmland. As soon as I place the second seed, both pop off. I will test in an environment with only AM at a later time, but in my WIP pack it happens every time.

**Comment by McJty** [comment]
How much light does the farmland get?

**Comment by davqvist** [comment]
I didn't check, will do, but I doubt that was the problem as I tested at day under open sky.

**Comment by McJty** [comment]
Well clueless... I cannot reproduce this at all

**Comment by davqvist** [comment]
I created a new instance, Forge 2474.
I only added JEI, The One Probe, ImmersiveCraft, Aqua Munda and also Botania, Baubles and Primal Core because I tested also something else. But Botania, Baubles and Primal Core were not in the old instance, so that for certain doesn't matter. I created a new world, cheated in a hoe, hoed two grass next to each other, cheated in some beetroot seeds, planted them and they popped off. Light was 15.

**Comment by davqvist** [comment]
I know you are busy with some awesome RFTools features, but were you able to investigate that further? Or do you need more info? I can replicate it constantly like described above.

**Comment by McJty** [comment]
At the moment no. I still was not able to reproduce it either

**Comment by davqvist** [comment]
I would still like to get this fixed. Any updates on it? Still happening even with vanilla Beetroot.

**Comment by McJty** [comment]
I cannot fix problems I cannot replicate. I have no clue how to go further on this to be honest

**Comment by McJty** [comment]
Can you show some screenshots? Also what config are you using for Aqua Munda?

**Comment by davqvist** [comment]
Config: https://pastebin.com/SzsyhVU7
Not sure how screenshots are better than the videos from above, but here you go: https://imgur.com/hRQMPlX

It confuses me how you are not able to reproduce it. I can replicate in a new world with only the few mods installed above. I am willing to help you with everything you need to know, just let me know what you want to have/know.

**Comment by davqvist** [comment]
Let me test in a fresh world with only AM

**Comment by McJty** [comment]
And you have a fresh water source nearby?

**Comment by davqvist** [comment]
No fresh water, but they still shouldn't pop off, right?

**Comment by davqvist** [comment]
Can confirm in fresh world with only JEI, TOP, ImmersiveCraft and Aqua Munda
Forge 2556

**Comment by McJty** [comment]
Do they pop off if there is fresh water nearby? If not then that's the reason

**Comment by davqvist** [comment]
Well, that is the whole point of the issue as you can see in the title. That they pop off without fresh water. Other vanilla plants don't do that, only Beetroot or some other modded seeds.

**Comment by davqvist** [comment]
Anyway, they pop off even with Fresh Water fwiw

**Comment by davqvist** [comment]
https://imgur.com/1JFrciy

**Comment by McJty** [comment]
Ok, I can reproduce it now. Seems it only happens if you plant seeds next to each other. If you give them room they don't pop off
Not sure why though

**Comment by davqvist** [comment]
Yep exactly. I have no clue either. Has to be something Beetroot specific.

**Comment by davqvist** [comment]
If it helps, not being next to each other is the cause as written in the initial post, but rather a block update causes it.

**Comment by McJty** [comment]
I know what's wrong. Just have to come up with a good solution for this

**Comment by davqvist** [comment]
Awesome, thank you very much

**Comment by McJty** [comment]
Sorry for the slow response but this is fixed next release

**Comment by davqvist** [comment]
Excellent, thanks very much
