### ISSUE TITLE
[Suggestion/Question] Grindstone Support / Meta Data Syntax

### ISSUE THREAD

**Issue by MasterEnderman** [McJty/AquaMunda#21]
I know you are already able to specify recipes for the cooker and cutting board. Now is it possible to add this method for the grindstone too?

I tried to add recipes using Items with meta data and I can't get the recipes working. Is there are special syntax you have to write the item name instead of e.g. minecraft:wool:5 ?

**Comment by McJty** [comment]
Grindstone recipe configuration implemented for next release (soon). Checking out the metadata support in a moment

**Comment by McJty** [comment]
The syntax for meta is minecraft:wool@5
