### ISSUE TITLE
blooper in recipe for manual

### ISSUE THREAD

**Issue by barrowisp** [McJty/AquaMunda#28]
Heya, 
I noticed that the recipe JSONs for both board_manual and grindstone_manual have aquamunda:board_manual listed as the recipe result.
![aqua manuals](https://user-images.githubusercontent.com/47377677/54007196-797f1100-4115-11e9-8a71-ac23a0c77d45.PNG)
In SSP, the crafting table's result field shows Cutting Board Manual whether I put a knife or bone in the ingredients field.
![board manual](https://user-images.githubusercontent.com/47377677/54014628-34b5a300-4132-11e9-842f-e5763f7d5181.png)
![problem manual](https://user-images.githubusercontent.com/47377677/54014629-34b5a300-4132-11e9-9dc2-8d8ee5de00dc.png)

Cheers!

**Comment by McJty** [comment]
Fixed next release
