### ISSUE TITLE
fresh bucket problems

### ISSUE THREAD

**Issue by ewsmith** [McJty/AquaMunda#3]
using a bucket on a tank with fresh water makes the bucket disappear.
using a fresh water bucket that was creatively spawned on a cooker does nothing.

sorry about breaking all the things :c 

also: is the sprinkler supposed to water the farmland. it currently needs a water source 
to keep the farmland from decaying into dirt.

**Comment by McJty** [comment]
What version of Aqua Munda?

**Comment by ewsmith** [comment]
0.0.4beta

**Comment by McJty** [comment]
And what version of Minecraft? This could be MC version specific

**Comment by McJty** [comment]
And yes about the sprinkler if you configured it that way. If I understand the question correctly

**Comment by ewsmith** [comment]
minecraft 1.10.2

**Comment by ewsmith** [comment]
so, the sprinkler will hydrate the farmland without a source block on harsh?

**Comment by McJty** [comment]
Ah no, you still need the source block. In harsh mode however, not using  a sprinkler will kill the plant eventually.

**Comment by McJty** [comment]
Anyway, I can reproduce your tank/bucket problems on 1.10. Fixing them

**Comment by McJty** [comment]
Fixed
