### ISSUE TITLE
Hose Crash in 0.1.0 on MC 1.10.2

### ISSUE THREAD

**Issue by DnielMC** [McJty/AquaMunda#6]
Just placed a hose randomly in the world. Rest should be in the pastebin.
http://pastebin.com/fVxG5Bsx

**Comment by McJty** [comment]
I cannot reproduce this. Does this happen all the time?

**Comment by McJty** [comment]
Even though I cannot reproduce it someone else also reported it. I added a test for this so next version should fix this
