### ISSUE TITLE
Creative Tab localization string isn't being applied

### ISSUE THREAD

**Issue by WesCook** [McJty/AquaMunda#8]
In the lang file, there's no space: `itemGroup.AquaMunda`.

In the code, [there is](https://github.com/McJty/AquaMunda/blob/667dbb6f5c0cbf50451bb4e8c69238d7e869da2b/src/main/java/mcjty/aquamunda/AquaMunda.java#L66).

As a result, the localization does not apply.

![2017-02-11 20_36_11-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/792101/22859690/c703241c-f099-11e6-9e82-66764e97aed3.png)

**Comment by McJty** [comment]
Fixed next release
